FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /opt/app-root/db/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /opt/app-root/db/requirements.txt

# Set environment variables
ENV PYTHONPATH /opt/app-root/db
ENV PYTHONUNBUFFERED=1

# Make port 8000 available to the world outside this container
EXPOSE 8100

CMD ["gunicorn", "--config", "/opt/app-root/db/db_app/api/settings/gunicorn.conf.py"]